- name: Create Jenkins security group
  ec2_group:
      name: jenkins
      description: Infrastructure for Jenkins server
      region: "{{ ec2_region }}"
      rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0

      rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
  register: jenkins
