- hosts: launched
  remote_user: ubuntu
  sudo: yes

  tasks:

  - name: Upgrade
    command: apt-get upgrade -y

  - name: add repo
    command: add-apt-repository ppa:webupd8team/java -y

  - name: Update
    command: apt-get update -y

  - name: Install java
    apt:
      name: oracle-java8-installer
      state: present
    
  - name: Set up environment variables
    apt:
      name: oracle-java8-set-default

