- hosts: launched
  remote_user: ubuntu
  sudo: yes
  vars:
    
    JAVA_OPTIONS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
    download_key: https://pkg.jenkins.io/debian/jenkins-ci.org.key

  tasks:
  
  - name: install default-jre
    apt:
      name: openjdk-8-jre
      state: present

  - apt_key:
      url: '{{download_key}}'
      state: present

  - name: echo
    command: sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list'

  - name: update
    command: apt-get update

  - name: Install jenkins
    apt:
      name: jenkins
      state: present

  - name: Change Jenkins options
    lineinfile:
      dest=/etc/default/jenkins
      regexp=^JENKINS_JAVA_OPTIONS=
      line=JENKINS_JAVA_OPTIONS="{{JAVA_OPTIONS}}"
    become: true

  
  - name: Enable ufw
    command: ufw enable

  - name: Activate firewall
    ufw:
      rule: allow
      name: OpenSSH
      state: enabled

  - name: Open port 8080
    ufw:
      rule: allow
      port: 8080

  - name: start jenkins
    service: name=jenkins state=started

  - name: Wait for file structure to load
    wait_for:
      path: /var/lib/jenkins/config.xml

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: '<useSecurity>'
      line: '  <useSecurity>true</useSecurity>'

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "<authorizationStrategy"
      state: absent
    
  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "  <denyAnonymousReadAccess>"
      state: absent

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "</authorizationStrategy>"
      state: absent

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "<securityRealm class"
      state: absent

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "  <disableSignup>true"
      state: absent

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "  <enableCaptcha>false</enableCaptcha>"
      state: absent

  - name: Disable Security
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: "</securityRealm>"
      state: absent

  
  - name: "Turn off Jenkins setup wizard"
    lineinfile:
        dest: /etc/init.d/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
        insertbefore: '^DAEMON_ARGS='

  - name: restart jenkins
    service: name=jenkins state=restarted

